language: node_js
node_js:
 - 8
install:
 - npm install
script: 
 - echo hola mundo
 - npm run echotest
 - npm run test
deploy:
  provider: heroku
  api_key:
    secure: c0352b31-1ab4-4dbe-a181-9fd79051b533
  app: travistestrichi